# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

wipe_pedigrees <- function(pedigrees) {
    invisible(.Call('malan_wipe_pedigrees', PACKAGE = 'malan', pedigrees))
}

#' Build pedigrees
#' 
#' @export
build_pedigrees <- function(population, progress = TRUE) {
    .Call('malan_build_pedigrees', PACKAGE = 'malan', population, progress)
}

#' @export
sample_geneology <- function(population_size, generations, progress = TRUE, individuals_generations_return = 2L, verbose_result = FALSE) {
    .Call('malan_sample_geneology', PACKAGE = 'malan', population_size, generations, progress, individuals_generations_return, verbose_result)
}

#' @export
sample_person_weighted <- function(population_size, fathers_prob_cum, fathers_perm) {
    .Call('malan_sample_person_weighted', PACKAGE = 'malan', population_size, fathers_prob_cum, fathers_perm)
}

#' @export
sample_geneology_variance <- function(population_size, generations, gamma_parameter_shape, gamma_parameter_scale, progress = TRUE, individuals_generations_return = 2L, verbose_result = FALSE) {
    .Call('malan_sample_geneology_variance', PACKAGE = 'malan', population_size, generations, gamma_parameter_shape, gamma_parameter_scale, progress, individuals_generations_return, verbose_result)
}

#' @export
pedigree_get_father_haplotypes_pids <- function(population, pids) {
    .Call('malan_pedigree_get_father_haplotypes_pids', PACKAGE = 'malan', population, pids)
}

#' @export
pedigree_populate_father_haplotypes <- function(ped, loci, mutation_rates) {
    invisible(.Call('malan_pedigree_populate_father_haplotypes', PACKAGE = 'malan', ped, loci, mutation_rates))
}

#' @export
pedigrees_all_populate_father_haplotypes <- function(pedigrees, loci, mutation_rates, progress = TRUE) {
    invisible(.Call('malan_pedigrees_all_populate_father_haplotypes', PACKAGE = 'malan', pedigrees, loci, mutation_rates, progress))
}

#' @export
pedigree_get_father_haplotype <- function(individual) {
    .Call('malan_pedigree_get_father_haplotype', PACKAGE = 'malan', individual)
}

#' @export
count_father_haplotype_occurrences_individuals <- function(individuals, haplotype) {
    .Call('malan_count_father_haplotype_occurrences_individuals', PACKAGE = 'malan', individuals, haplotype)
}

#' @export
meiosis_dist_father_haplotype_matches_individuals <- function(suspect, individuals) {
    .Call('malan_meiosis_dist_father_haplotype_matches_individuals', PACKAGE = 'malan', suspect, individuals)
}

#' @export
pedigree_father_haplotype_matches_in_pedigree_meiosis_L1_dists <- function(suspect, generation_upper_bound_in_result = -1L) {
    .Call('malan_pedigree_father_haplotype_matches_in_pedigree_meiosis_L1_dists', PACKAGE = 'malan', suspect, generation_upper_bound_in_result)
}

#' @export
count_father_haplotype_occurrences_pedigree <- function(pedigree, haplotype, generation_upper_bound_in_result = -1L) {
    .Call('malan_count_father_haplotype_occurrences_pedigree', PACKAGE = 'malan', pedigree, haplotype, generation_upper_bound_in_result)
}

get_individual <- function(population, pid) {
    .Call('malan_get_individual', PACKAGE = 'malan', population, pid)
}

#' @export
get_pid <- function(individual) {
    .Call('malan_get_pid', PACKAGE = 'malan', individual)
}

#' @export
print_individual <- function(individual) {
    invisible(.Call('malan_print_individual', PACKAGE = 'malan', individual))
}

#' Get pedigree from individual
#' 
#' @export
get_pedigree_from_individual <- function(individual) {
    .Call('malan_get_pedigree_from_individual', PACKAGE = 'malan', individual)
}

#' Get pedigree id from pid
#' 
#' @export
get_pedigree_id_from_pid <- function(population, pids) {
    .Call('malan_get_pedigree_id_from_pid', PACKAGE = 'malan', population, pids)
}

malan_test <- function() {
    invisible(.Call('malan_malan_test', PACKAGE = 'malan'))
}

pop_size <- function(population) {
    .Call('malan_pop_size', PACKAGE = 'malan', population)
}

#' @export
meioses_generation_distribution <- function(individual, generation_upper_bound_in_result = -1L) {
    .Call('malan_meioses_generation_distribution', PACKAGE = 'malan', individual, generation_upper_bound_in_result)
}

#' @export
population_size_generation <- function(population, generation_upper_bound_in_result = -1L) {
    .Call('malan_population_size_generation', PACKAGE = 'malan', population, generation_upper_bound_in_result)
}

#' @export
pedigree_size_generation <- function(pedigree, generation_upper_bound_in_result = -1L) {
    .Call('malan_pedigree_size_generation', PACKAGE = 'malan', pedigree, generation_upper_bound_in_result)
}

#' Get number of pedigrees
#' 
#' @export
pedigrees_count <- function(pedigrees) {
    .Call('malan_pedigrees_count', PACKAGE = 'malan', pedigrees)
}

#' Get pedigree size
#' 
#' @export
pedigree_size <- function(ped) {
    .Call('malan_pedigree_size', PACKAGE = 'malan', ped)
}

#' Get distribution of pedigree sizes
#' 
#' @export
pedigrees_table <- function(pedigrees) {
    .Call('malan_pedigrees_table', PACKAGE = 'malan', pedigrees)
}

get_pedigree <- function(pedigrees, index) {
    .Call('malan_get_pedigree', PACKAGE = 'malan', pedigrees, index)
}

print_pedigree <- function(ped) {
    invisible(.Call('malan_print_pedigree', PACKAGE = 'malan', ped))
}

#' get pids in pedigree
#' 
#' @export
get_pids_in_pedigree <- function(ped) {
    .Call('malan_get_pids_in_pedigree', PACKAGE = 'malan', ped)
}

get_pedigree_edgelist <- function(ped) {
    .Call('malan_get_pedigree_edgelist', PACKAGE = 'malan', ped)
}

#' Get pedigree information as graph (mainly intended for plotting)
#' 
#' @export
get_pedigree_as_graph <- function(ped) {
    .Call('malan_get_pedigree_as_graph', PACKAGE = 'malan', ped)
}

